version: '2'

services:

    sonarqube:
        image: sonarqube
        volumes:
            - ./sonar_data/plugins/sonar-pmd-plugin-3.2.0-SNAPSHOT.jar:/opt/sonarqube/extensions/plugins/sonar-pmd-plugin-3.2.0-SNAPSHOT.jar
        ports:
            - "9001:9000"
        links:
            - postgres
        environment:
            - SONARQUBE_JDBC_URL:jdbc:postgresql://db:5432/sonar

    postgres:
        image: postgres
        volumes:
        - ./postgres_data:/var/lib/postgresql/data
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
