version: '2.1'
services:
    zookeeper:
        image: 'zookeeper:3.4.14'
        ports:
            - '2181:2181'
        volumes:
            - ./config/zoo.cfg:/opt/zookeeper-3.4.14/conf/zoo.cfg
            - ./data/zookeeper:/data/zookeeper

    kafka:
        image: 'wurstmeister/kafka:2.12-2.2.0'
        ports:
            - '9092:9092'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            # 本机ip
            KAFKA_ADVERTISED_HOST_NAME: 10.10.24.208
            KAFKA_CREATE_TOPICS: "test:1:1"
        volumes:
            - ./data/kafka:/data/kafka-logs
