version: '2'
services:
  es01:
    image: elasticsearch:6.7.1
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./es/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/plugins/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: elasticsearch:6.7.1
    container_name: es02
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./es/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/plugins/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - 9201:9200
    links:
      - es01
    networks:
      - esnet
  es03:
    image: elasticsearch:6.7.1
    container_name: es03
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./es/es3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/plugins/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - 9202:9200
    links:
      - es01
    networks:
      - esnet
  kibana:
    image: kibana:6.7.1
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    # environment:
    #   - server.name= kibana
    #   - server.host= 0
    #   - elasticsearch.hosts= http://es01:9200
    #   - xpack.monitoring.ui.container.elasticsearch.enabled= true
    #   - i18n.locale= zh-CN
    networks:
      - esnet
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
networks:
  esnet:
    driver: bridge
